// <auto-generated />

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage(
    "Naming",
    "CA1711:Identifiers should not have incorrect suffix",
    Justification = "Public API preserved for scripting compatibility.",
    Scope = "type",
    Target = "~T:NovaSharp.Interpreter.DataTypes.ScriptFunctionDelegate"
)]
[assembly: SuppressMessage(
    "Naming",
    "CA1711:Identifiers should not have incorrect suffix",
    Justification = "Public API preserved for scripting compatibility.",
    Scope = "type",
    Target = "~T:NovaSharp.Interpreter.DataTypes.ScriptFunctionDelegate`1"
)]
[assembly: SuppressMessage(
    "Naming",
    "CA1711:Identifiers should not have incorrect suffix",
    Justification = "Historical name preserved for backwards compatibility.",
    Scope = "type",
    Target = "~T:NovaSharp.Interpreter.DataTypes.TypeValidationFlags"
)]
[assembly: SuppressMessage(
    "Naming",
    "CA1720:Identifier contains type name",
    Justification = "Matches Lua-facing API terminology.",
    Scope = "type",
    Target = "~T:NovaSharp.Interpreter.DataTypes.DynValue"
)]
[assembly: SuppressMessage(
    "Naming",
    "CA1720:Identifier contains type name",
    Justification = "Matches Lua-facing API terminology.",
    Scope = "type",
    Target = "~T:NovaSharp.Interpreter.DataTypes.UserData"
)]
[assembly: SuppressMessage(
    "Design",
    "CA1819:Properties should not return arrays",
    Justification = "Exposed for Lua tuple interop.",
    Scope = "type",
    Target = "~T:NovaSharp.Interpreter.DataTypes.DynValue"
)]
[assembly: SuppressMessage(
    "Design",
    "CA1819:Properties should not return arrays",
    Justification = "Interoperability surface requires array access.",
    Scope = "type",
    Target = "~T:NovaSharp.Interpreter.DataTypes.TailCallData"
)]
[assembly: SuppressMessage(
    "Design",
    "CA1819:Properties should not return arrays",
    Justification = "Yield requests expose arguments to scripting hosts.",
    Scope = "type",
    Target = "~T:NovaSharp.Interpreter.DataTypes.YieldRequest"
)]
[assembly: SuppressMessage(
    "Design",
    "CA1043:Use Integral Or String Argument For Indexers",
    Justification = "Lua tables use dynamic keys for interoperability.",
    Scope = "type",
    Target = "~T:NovaSharp.Interpreter.DataTypes.Table"
)]
[assembly: SuppressMessage(
    "Naming",
    "CA1707:Identifiers should not contain underscores",
    Justification = "Matches original Lua constant names.",
    Scope = "type",
    Target = "~T:NovaSharp.Interpreter.Interop.LuaStateInterop.LuaBase"
)]
[assembly: SuppressMessage(
    "Design",
    "CA1051:Do not declare visible instance fields",
    Justification = "Interop pointer semantics require field access.",
    Scope = "type",
    Target = "~T:NovaSharp.Interpreter.Interop.LuaStateInterop.CharPtr"
)]
[assembly: SuppressMessage(
    "Usage",
    "CA2225:Operator overloads have named alternates",
    Justification = "Interop pointer type intentionally mirrors native Lua semantics.",
    Scope = "type",
    Target = "~T:NovaSharp.Interpreter.Interop.LuaStateInterop.CharPtr"
)]
[assembly: SuppressMessage(
    "Design",
    "CA1052:Static holder types should be Static or NotInheritable",
    Justification = "Modules are discovered and instantiated via generic registration.",
    Scope = "type",
    Target = "~T:NovaSharp.Interpreter.CoreLib.TableModule"
)]
[assembly: SuppressMessage(
    "Design",
    "CA1052:Static holder types should be Static or NotInheritable",
    Justification = "Modules are discovered and instantiated via generic registration.",
    Scope = "type",
    Target = "~T:NovaSharp.Interpreter.CoreLib.TableModuleGlobals"
)]
[assembly: SuppressMessage(
    "Design",
    "CA1052:Static holder types should be Static or NotInheritable",
    Justification = "Modules are discovered and instantiated via generic registration.",
    Scope = "type",
    Target = "~T:NovaSharp.Interpreter.CoreLib.TableIteratorsModule"
)]
[assembly: SuppressMessage(
    "Design",
    "CA1052:Static holder types should be Static or NotInheritable",
    Justification = "Modules are discovered and instantiated via generic registration.",
    Scope = "type",
    Target = "~T:NovaSharp.Interpreter.CoreLib.MetaTableModule"
)]
[assembly: SuppressMessage(
    "Design",
    "CA1052:Static holder types should be Static or NotInheritable",
    Justification = "Modules are discovered and instantiated via generic registration.",
    Scope = "type",
    Target = "~T:NovaSharp.Interpreter.CoreLib.StringModule"
)]
[assembly: SuppressMessage(
    "Naming",
    "CA1707:Identifiers should not contain underscores",
    Justification = "Constant names mirror Lua's global names.",
    Scope = "type",
    Target = "~T:NovaSharp.Interpreter.CoreLib.StringModule"
)]
[assembly: SuppressMessage(
    "Design",
    "CA1052:Static holder types should be Static or NotInheritable",
    Justification = "Interop helper members mimic native Lua API surfaces.",
    Scope = "type",
    Target = "~T:NovaSharp.Interpreter.Interop.LuaStateInterop.LuaBase"
)]
[assembly: SuppressMessage(
    "Naming",
    "CA1721:Property names should not match get methods",
    Justification = "Preserves existing scripting API for member descriptors.",
    Scope = "type",
    Target = "~T:NovaSharp.Interpreter.Interop.StandardDescriptors.MemberDescriptors.DynValueMemberDescriptor"
)]
