---
extends: default

rules:
  document-start: disable
  line-length: disable
  truthy:
    allowed-values:
      - "true"
      - "false"
      - "on"
      - "off"
    check-keys: false

ignore: |
  artifacts/
  docs/coverage/
  src/**/bin/
  src/**/obj/
