<#
.SYNOPSIS
    Generates FixtureCatalogGenerated.cs listing all NUnit [TestFixture] types so analyzers
    observe the fixtures even when they become internal.

.DESCRIPTION
    Scans the WallstopStudios.NovaSharp.Interpreter.Tests project for `[TestFixture]` declarations and emits a
    generated file that references every discovered type via `typeof(...)`. This keeps CA1812 and
    CA1515 satisfied once fixtures are made internal because the compiler now sees explicit usage.

.USAGE
    pwsh ./scripts/tests/update-fixture-catalog.ps1
#>

param(
    [string]$TestsRoot = "src/tests/WallstopStudios.NovaSharp.Interpreter.Tests",
    [string]$OutputPath = "src/tests/WallstopStudios.NovaSharp.Interpreter.Tests/FixtureCatalogGenerated.cs"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Get-FixtureTypeNames {
    param([string]$Root)

    $fixtures = [System.Collections.Generic.List[string]]::new()

    Get-ChildItem -Path $Root -Filter *.cs -Recurse | ForEach-Object {
        $namespace = $null
        $pendingFixture = $false

        foreach ($line in Get-Content -LiteralPath $_.FullName) {
            if ($line -match '^\s*namespace\s+([A-Za-z0-9_.]+)') {
                $namespace = $matches[1]
                continue
            }

            if ($line -match '\[TestFixture') {
                $pendingFixture = $true
                continue
            }

            if ($pendingFixture) {
                if ($line -match '^\s*(public|internal)\s+(?:sealed\s+|static\s+|abstract\s+)?class\s+([A-Za-z0-9_`]+)') {
                    if (-not $namespace) {
                        throw "Missing namespace declaration in $($_.FullName)"
                    }

                    $fixtures.Add("global::$namespace.$($matches[2])")
                    $pendingFixture = $false
                    continue
                }

                if ($line.Trim().Length -eq 0 -or $line.TrimStart().StartsWith("[", [System.StringComparison]::Ordinal)) {
                    continue
                }

                $pendingFixture = $false
            }
        }
    }

    return @($fixtures | Sort-Object -Unique)
}

$fixtureTypes = @(Get-FixtureTypeNames -Root $TestsRoot)

# Use CRLF to match .gitattributes (*.cs text eol=crlf) for cross-platform consistency
$crlf = "`r`n"

# Build content with explicit CRLF line endings (avoid here-strings which use platform-native endings)
$headerLines = @(
    "// <auto-generated />"
    "// Generated by scripts/tests/update-fixture-catalog.ps1"
    "namespace WallstopStudios.NovaSharp.Interpreter.Tests"
    "{"
    "    using System;"
    "    using System.Diagnostics.CodeAnalysis;"
    ""
    "    [ExcludeFromCodeCoverage]"
    "    internal static class FixtureCatalog"
    "    {"
    "        private static readonly Type[] ReferencedFixtures = new Type[]"
    "        {"
)

$footerLines = @(
    "        };"
    ""
    "        static FixtureCatalog()"
    "        {"
    "            _ = ReferencedFixtures.Length;"
    "        }"
    "    }"
    "}"
)

if ($fixtureTypes.Count -eq 0) {
    $bodyLines = @("            // No NUnit fixtures remain.")
}
else {
    $bodyLines = $fixtureTypes | ForEach-Object { "            typeof($_)," }
}

$allLines = $headerLines + $bodyLines + $footerLines
$content = ($allLines -join $crlf) + $crlf

# Write with explicit encoding and no BOM
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText((Resolve-Path $OutputPath -ErrorAction SilentlyContinue)?.Path ?? (Join-Path (Get-Location) $OutputPath), $content, $utf8NoBom)
Write-Host "Generated $OutputPath with $($fixtureTypes.Count) fixtures."

