// <auto-generated/>
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage(
    "Usage",
    "CA1515:Consider making public types internal",
    Justification = "BenchmarkDotNet comparison harnesses keep their scenarios public for reflective discovery.",
    Scope = "module")]
