namespace NovaSharp.Interpreter.Tree.Lexer
{
    using System;

    internal enum TokenType
    {
        [Obsolete("Use a specific TokenType.", false)]
        Unknown = 0,
        Eof = 1,
        HashBang = 2,
        Name = 3,
        And = 4,
        Break = 5,
        Do = 6,
        Else = 7,
        ElseIf = 8,
        End = 9,
        False = 10,
        For = 11,
        Function = 12,
        Lambda = 13,
        Goto = 14,
        If = 15,
        In = 16,
        Local = 17,
        Nil = 18,
        Not = 19,
        Or = 20,
        Repeat = 21,
        Return = 22,
        Then = 23,
        True = 24,
        Until = 25,
        While = 26,
        OpEqual = 27,
        OpAssignment = 28,
        OpLessThan = 29,
        OpLessThanEqual = 30,
        OpGreaterThanEqual = 31,
        OpGreaterThan = 32,
        OpNotEqual = 33,
        OpConcat = 34,
        VarArgs = 35,
        Dot = 36,
        Colon = 37,
        DoubleColon = 38,
        Comma = 39,
        BrkCloseCurly = 40,
        BrkOpenCurly = 41,
        BrkCloseRound = 42,
        BrkOpenRound = 43,
        BrkCloseSquare = 44,
        BrkOpenSquare = 45,
        OpLen = 46,
        OpPwr = 47,
        OpMod = 48,
        OpDiv = 49,
        OpMul = 50,
        OpMinusOrSub = 51,
        OpAdd = 52,
        Comment = 53,
        String = 54,
        StringLong = 55,
        Number = 56,
        NumberHexFloat = 57,
        NumberHex = 58,
        SemiColon = 59,
        Invalid = 60,
        BrkOpenCurlyShared = 61,
        OpDollar = 62,
    }
}
