// <auto-generated />
// Generated by scripts/tests/update-fixture-catalog.ps1
namespace WallstopStudios.NovaSharp.Interpreter.Tests
{
    using System;
    using System.Diagnostics.CodeAnalysis;

    [ExcludeFromCodeCoverage]
    internal static class FixtureCatalog
    {
        private static readonly Type[] ReferencedFixtures = new Type[]
        {
            // No NUnit fixtures remain.
        };

        static FixtureCatalog()
        {
            _ = ReferencedFixtures.Length;
        }
    }
}
