// <auto-generated />
// Generated by scripts/tests/update-fixture-catalog.ps1
namespace NovaSharp.Interpreter.Tests
{
    using System;
    using System.Diagnostics.CodeAnalysis;

    [ExcludeFromCodeCoverage]
    internal static class FixtureCatalog
    {
        private static readonly Type[] ReferencedFixtures = new Type[]
        {
            typeof(global::NovaSharp.Interpreter.Tests.Units.Debugging.SourceRefTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.Debugging.WatchItemTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.DotNetCorePlatformAccessorTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.ErrorHandlingModuleTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.FastStackDynamicTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.InstructionFieldUsageExtensionsTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.InteropTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.ModManifestCompatibilityTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.ModManifestTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.PathSpanExtensionsTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.PerformanceStatisticsTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.SerializationExtensionsTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.SourceRefTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.UndisposableStreamTests),
};

        static FixtureCatalog()
        {
            _ = ReferencedFixtures.Length;
        }
    }
}
