// <auto-generated />
// Generated by scripts/tests/update-fixture-catalog.ps1
namespace NovaSharp.Interpreter.Tests
{
    using System;
    using System.Diagnostics.CodeAnalysis;

    [ExcludeFromCodeCoverage]
    internal static class FixtureCatalog
    {
        private static readonly Type[] ReferencedFixtures = new Type[]
        {
            typeof(global::NovaSharp.Interpreter.Tests.EndToEnd.BinaryDumpTests),
            typeof(global::NovaSharp.Interpreter.Tests.EndToEnd.ClosureTests),
            typeof(global::NovaSharp.Interpreter.Tests.EndToEnd.CollectionsRegisteredTests),
            typeof(global::NovaSharp.Interpreter.Tests.EndToEnd.ConfigPropertyAssignerTests),
            typeof(global::NovaSharp.Interpreter.Tests.EndToEnd.CoroutineTests),
            typeof(global::NovaSharp.Interpreter.Tests.EndToEnd.DynamicTests),
            typeof(global::NovaSharp.Interpreter.Tests.EndToEnd.ErrorHandlingTests),
            typeof(global::NovaSharp.Interpreter.Tests.EndToEnd.GotoTests),
            typeof(global::NovaSharp.Interpreter.Tests.EndToEnd.JsonSerializationTests),
            typeof(global::NovaSharp.Interpreter.Tests.EndToEnd.MetatableTests),
            typeof(global::NovaSharp.Interpreter.Tests.EndToEnd.ProxyObjectsTests),
            typeof(global::NovaSharp.Interpreter.Tests.EndToEnd.RealWorldScriptTests),
            typeof(global::NovaSharp.Interpreter.Tests.EndToEnd.SimpleTests),
            typeof(global::NovaSharp.Interpreter.Tests.EndToEnd.StringLibTests),
            typeof(global::NovaSharp.Interpreter.Tests.EndToEnd.StructAssignmentTechnique),
            typeof(global::NovaSharp.Interpreter.Tests.EndToEnd.TableTests),
            typeof(global::NovaSharp.Interpreter.Tests.EndToEnd.TailCallTests),
            typeof(global::NovaSharp.Interpreter.Tests.EndToEnd.VarargsTupleTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.AdjustmentExpressionTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.CloseAttributeTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.ClosureContextTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.ClosureTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.CompatibilityDiagnosticsTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.DataStructs.SliceTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.Debugging.SourceRefTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.Debugging.WatchItemTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.DotNetCorePlatformAccessorTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.DynamicExprExpressionTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.DynamicModuleTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.EnumerableWrapperTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.ErrorHandlingModuleTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.EventFacadeTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.EventMemberDescriptorTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.ExprListExpressionTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.FastStackDynamicTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.FastStackTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.HardwiredDescriptorsTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.HardwireGeneratorRegistryTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.HardwireGeneratorTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.IndexExpressionTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.InfrastructureTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.InstructionFieldUsageExtensionsTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.InteropTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.InterpreterExceptionTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.JsonNullTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.JsonTableConverterTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.LexerUtilsTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.LiteralExpressionTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.MetatableTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.ModManifestCompatibilityTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.ModManifestTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.MultiDictionaryTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.NodeBaseTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.OsSystemModuleTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.OsTimeModuleTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.ParameterDescriptorTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.ParserTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.PathSpanExtensionsTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.PerformanceStatisticsTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.ProgramTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.PropertyTableAssignerTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.ReflectionSpecialNamesTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.ReplHistoryInterpreterTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.ReplInterpreterTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.SerializationExtensionsTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.SliceTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.SourceRefTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.StandardGenericsUserDataDescriptorTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.StandardIoFileUserDataBaseTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.StandardPlatformAccessorTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.StreamFileUserDataBaseTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.SymbolRefTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.SyntaxErrorExceptionTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.TokenTests),
            typeof(global::NovaSharp.Interpreter.Tests.Units.UndisposableStreamTests),
};

        static FixtureCatalog()
        {
            _ = ReferencedFixtures.Length;
        }
    }
}
